[tool.poetry]
name = "neonfc-ssl"
version = "0.1.0"
description = ""
authors = ["Alexsandro Santos <alexsandro2134@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
protobuf = "3.20.x"
scipy = "^1.11.3"
numpy = "^1.26.0"
serial = "^0.0.97"
pyserial = "^3.5"
neonpathplanning = "^1.0.1"
matplotlib = "^3.9.2"
pyvisgraph = "^0.2.1"
tqdm = "^4.66.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
