# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: decision.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import commons_pb2 as commons__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='decision.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x64\x65\x63ision.proto\x1a\rcommons.proto\"J\n\rDecisionRobot\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1b\n\ntarget_pos\x18\x02 \x01(\x0b\x32\x07.Vector\x12\x10\n\x08strategy\x18\x03 \x01(\t\"H\n\x08\x44\x65\x63ision\x12\x12\n\x05\x63oach\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1e\n\x06robots\x18\x02 \x03(\x0b\x32\x0e.DecisionRobotB\x08\n\x06_coachb\x06proto3'
  ,
  dependencies=[commons__pb2.DESCRIPTOR,])




_DECISIONROBOT = _descriptor.Descriptor(
  name='DecisionRobot',
  full_name='DecisionRobot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DecisionRobot.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_pos', full_name='DecisionRobot.target_pos', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strategy', full_name='DecisionRobot.strategy', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=107,
)


_DECISION = _descriptor.Descriptor(
  name='Decision',
  full_name='Decision',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='coach', full_name='Decision.coach', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='robots', full_name='Decision.robots', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_coach', full_name='Decision._coach',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=109,
  serialized_end=181,
)

_DECISIONROBOT.fields_by_name['target_pos'].message_type = commons__pb2._VECTOR
_DECISION.fields_by_name['robots'].message_type = _DECISIONROBOT
_DECISION.oneofs_by_name['_coach'].fields.append(
  _DECISION.fields_by_name['coach'])
_DECISION.fields_by_name['coach'].containing_oneof = _DECISION.oneofs_by_name['_coach']
DESCRIPTOR.message_types_by_name['DecisionRobot'] = _DECISIONROBOT
DESCRIPTOR.message_types_by_name['Decision'] = _DECISION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DecisionRobot = _reflection.GeneratedProtocolMessageType('DecisionRobot', (_message.Message,), {
  'DESCRIPTOR' : _DECISIONROBOT,
  '__module__' : 'decision_pb2'
  # @@protoc_insertion_point(class_scope:DecisionRobot)
  })
_sym_db.RegisterMessage(DecisionRobot)

Decision = _reflection.GeneratedProtocolMessageType('Decision', (_message.Message,), {
  'DESCRIPTOR' : _DECISION,
  '__module__' : 'decision_pb2'
  # @@protoc_insertion_point(class_scope:Decision)
  })
_sym_db.RegisterMessage(Decision)


# @@protoc_insertion_point(module_scope)
