# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: neonfc.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from . import tracking_pb2 as tracking__pb2
from . import decision_pb2 as decision__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='neonfc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cneonfc.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0etracking.proto\x1a\x0e\x64\x65\x63ision.proto\"h\n\tLayerInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x11pipeline_position\x18\x02 \x01(\x05\x12\x1c\n\x06status\x18\x03 \x01(\x0e\x32\x0c.LayerStatus\x12\x14\n\x0crefresh_rate\x18\x04 \x01(\x02\"&\n\x04Game\x12\x1e\n\nlayer_info\x18\x01 \x03(\x0b\x32\n.LayerInfo\"\x85\x02\n\x08LogEntry\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x06source\x18\x02 \x01(\x0e\x32\x08.Sources\x12\r\n\x05level\x18\x03 \x01(\x05\x12\x14\n\x07message\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x04game\x18\x05 \x01(\x0b\x32\x05.GameH\x01\x88\x01\x01\x12 \n\x08tracking\x18\x06 \x01(\x0b\x32\t.TrackingH\x02\x88\x01\x01\x12 \n\x08\x64\x65\x63ision\x18\x07 \x01(\x0b\x32\t.DecisionH\x03\x88\x01\x01\x42\n\n\x08_messageB\x07\n\x05_gameB\x0b\n\t_trackingB\x0b\n\t_decision*l\n\x07Sources\x12\x08\n\x04GAME\x10\x00\x12\x0e\n\nINPUTLAYER\x10\x01\x12\x11\n\rTRACKINGLAYER\x10\x02\x12\x11\n\rDECISIONLAYER\x10\x03\x12\x10\n\x0c\x43ONTROLLAYER\x10\x04\x12\x0f\n\x0bOUTPUTLAYER\x10\x05*F\n\x0bLayerStatus\x12\x0f\n\x0bNOT_STARTED\x10\x00\x12\x0f\n\x0bNOT_RUNNING\x10\x01\x12\x08\n\x04IDLE\x10\x02\x12\x0b\n\x07RUNNING\x10\x03\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,tracking__pb2.DESCRIPTOR,decision__pb2.DESCRIPTOR,])

_SOURCES = _descriptor.EnumDescriptor(
  name='Sources',
  full_name='Sources',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GAME', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INPUTLAYER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TRACKINGLAYER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DECISIONLAYER', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONTROLLAYER', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OUTPUTLAYER', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=491,
  serialized_end=599,
)
_sym_db.RegisterEnumDescriptor(_SOURCES)

Sources = enum_type_wrapper.EnumTypeWrapper(_SOURCES)
_LAYERSTATUS = _descriptor.EnumDescriptor(
  name='LayerStatus',
  full_name='LayerStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_STARTED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NOT_RUNNING', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=601,
  serialized_end=671,
)
_sym_db.RegisterEnumDescriptor(_LAYERSTATUS)

LayerStatus = enum_type_wrapper.EnumTypeWrapper(_LAYERSTATUS)
GAME = 0
INPUTLAYER = 1
TRACKINGLAYER = 2
DECISIONLAYER = 3
CONTROLLAYER = 4
OUTPUTLAYER = 5
NOT_STARTED = 0
NOT_RUNNING = 1
IDLE = 2
RUNNING = 3



_LAYERINFO = _descriptor.Descriptor(
  name='LayerInfo',
  full_name='LayerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='LayerInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pipeline_position', full_name='LayerInfo.pipeline_position', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='LayerInfo.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='refresh_rate', full_name='LayerInfo.refresh_rate', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=185,
)


_GAME = _descriptor.Descriptor(
  name='Game',
  full_name='Game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='layer_info', full_name='Game.layer_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=225,
)


_LOGENTRY = _descriptor.Descriptor(
  name='LogEntry',
  full_name='LogEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='LogEntry.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='LogEntry.source', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='level', full_name='LogEntry.level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='LogEntry.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game', full_name='LogEntry.game', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tracking', full_name='LogEntry.tracking', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='decision', full_name='LogEntry.decision', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_message', full_name='LogEntry._message',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_game', full_name='LogEntry._game',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_tracking', full_name='LogEntry._tracking',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_decision', full_name='LogEntry._decision',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=228,
  serialized_end=489,
)

_LAYERINFO.fields_by_name['status'].enum_type = _LAYERSTATUS
_GAME.fields_by_name['layer_info'].message_type = _LAYERINFO
_LOGENTRY.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_LOGENTRY.fields_by_name['source'].enum_type = _SOURCES
_LOGENTRY.fields_by_name['game'].message_type = _GAME
_LOGENTRY.fields_by_name['tracking'].message_type = tracking__pb2._TRACKING
_LOGENTRY.fields_by_name['decision'].message_type = decision__pb2._DECISION
_LOGENTRY.oneofs_by_name['_message'].fields.append(
  _LOGENTRY.fields_by_name['message'])
_LOGENTRY.fields_by_name['message'].containing_oneof = _LOGENTRY.oneofs_by_name['_message']
_LOGENTRY.oneofs_by_name['_game'].fields.append(
  _LOGENTRY.fields_by_name['game'])
_LOGENTRY.fields_by_name['game'].containing_oneof = _LOGENTRY.oneofs_by_name['_game']
_LOGENTRY.oneofs_by_name['_tracking'].fields.append(
  _LOGENTRY.fields_by_name['tracking'])
_LOGENTRY.fields_by_name['tracking'].containing_oneof = _LOGENTRY.oneofs_by_name['_tracking']
_LOGENTRY.oneofs_by_name['_decision'].fields.append(
  _LOGENTRY.fields_by_name['decision'])
_LOGENTRY.fields_by_name['decision'].containing_oneof = _LOGENTRY.oneofs_by_name['_decision']
DESCRIPTOR.message_types_by_name['LayerInfo'] = _LAYERINFO
DESCRIPTOR.message_types_by_name['Game'] = _GAME
DESCRIPTOR.message_types_by_name['LogEntry'] = _LOGENTRY
DESCRIPTOR.enum_types_by_name['Sources'] = _SOURCES
DESCRIPTOR.enum_types_by_name['LayerStatus'] = _LAYERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LayerInfo = _reflection.GeneratedProtocolMessageType('LayerInfo', (_message.Message,), {
  'DESCRIPTOR' : _LAYERINFO,
  '__module__' : 'neonfc_pb2'
  # @@protoc_insertion_point(class_scope:LayerInfo)
  })
_sym_db.RegisterMessage(LayerInfo)

Game = _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), {
  'DESCRIPTOR' : _GAME,
  '__module__' : 'neonfc_pb2'
  # @@protoc_insertion_point(class_scope:Game)
  })
_sym_db.RegisterMessage(Game)

LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), {
  'DESCRIPTOR' : _LOGENTRY,
  '__module__' : 'neonfc_pb2'
  # @@protoc_insertion_point(class_scope:LogEntry)
  })
_sym_db.RegisterMessage(LogEntry)


# @@protoc_insertion_point(module_scope)
