# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracking.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import commons_pb2 as commons__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tracking.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0etracking.proto\x1a\rcommons.proto\"w\n\x08Geometry\x12\x14\n\x0c\x66ield_length\x18\x01 \x01(\x02\x12\x13\n\x0b\x66ield_width\x18\x02 \x01(\x02\x12\x12\n\ngoal_width\x18\x03 \x01(\x02\x12\x15\n\rpenalty_depth\x18\x04 \x01(\x02\x12\x15\n\rpenalty_width\x18\x05 \x01(\x02\"W\n\x05Robot\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x16\n\x05\x63olor\x18\x02 \x01(\x0e\x32\x07.Colors\x12\x14\n\x03pos\x18\x03 \x01(\x0b\x32\x07.Vector\x12\x14\n\x03vel\x18\x04 \x01(\x0b\x32\x07.Vector\"2\n\x04\x42\x61ll\x12\x14\n\x03pos\x18\x01 \x01(\x0b\x32\x07.Vector\x12\x14\n\x03vel\x18\x02 \x01(\x0b\x32\x07.Vector\"P\n\tGameState\x12\x1e\n\rcurrent_state\x18\x01 \x01(\x0e\x32\x07.States\x12\x1a\n\x04team\x18\x02 \x01(\x0e\x32\x07.ColorsH\x00\x88\x01\x01\x42\x07\n\x05_team\"\x1d\n\nPossession\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x02\"\x95\x02\n\x08Tracking\x12 \n\x08geometry\x18\x01 \x01(\x0b\x32\t.GeometryH\x00\x88\x01\x01\x12\x1b\n\nteam_color\x18\x02 \x01(\x0e\x32\x07.Colors\x12\x18\n\x04\x62\x61ll\x18\x03 \x01(\x0b\x32\x05.BallH\x01\x88\x01\x01\x12\x16\n\x06robots\x18\x04 \x03(\x0b\x32\x06.Robot\x12\x19\n\topposites\x18\x05 \x03(\x0b\x32\x06.Robot\x12#\n\ngame_state\x18\x06 \x01(\x0b\x32\n.GameStateH\x02\x88\x01\x01\x12$\n\npossession\x18\x07 \x01(\x0b\x32\x0b.PossessionH\x03\x88\x01\x01\x42\x0b\n\t_geometryB\x07\n\x05_ballB\r\n\x0b_game_stateB\r\n\x0b_possession*\x99\x01\n\x06States\x12\x08\n\x04HALT\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\x0b\n\x07TIMEOUT\x10\x02\x12\x13\n\x0fPREPARE_KICKOFF\x10\x03\x12\x13\n\x0fPREPARE_PENALTY\x10\x04\x12\x12\n\x0e\x42\x41LL_PLACEMENT\x10\x05\x12\x0b\n\x07KICKOFF\x10\x06\x12\r\n\tFREE_KICK\x10\x07\x12\x0b\n\x07PENALTY\x10\x08\x12\x07\n\x03RUN\x10\tb\x06proto3'
  ,
  dependencies=[commons__pb2.DESCRIPTOR,])

_STATES = _descriptor.EnumDescriptor(
  name='States',
  full_name='States',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HALT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TIMEOUT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PREPARE_KICKOFF', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PREPARE_PENALTY', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BALL_PLACEMENT', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='KICKOFF', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FREE_KICK', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PENALTY', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=689,
  serialized_end=842,
)
_sym_db.RegisterEnumDescriptor(_STATES)

States = enum_type_wrapper.EnumTypeWrapper(_STATES)
HALT = 0
STOP = 1
TIMEOUT = 2
PREPARE_KICKOFF = 3
PREPARE_PENALTY = 4
BALL_PLACEMENT = 5
KICKOFF = 6
FREE_KICK = 7
PENALTY = 8
RUN = 9



_GEOMETRY = _descriptor.Descriptor(
  name='Geometry',
  full_name='Geometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_length', full_name='Geometry.field_length', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='field_width', full_name='Geometry.field_width', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goal_width', full_name='Geometry.goal_width', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='penalty_depth', full_name='Geometry.penalty_depth', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='penalty_width', full_name='Geometry.penalty_width', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=152,
)


_ROBOT = _descriptor.Descriptor(
  name='Robot',
  full_name='Robot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Robot.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='Robot.color', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos', full_name='Robot.pos', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vel', full_name='Robot.vel', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=241,
)


_BALL = _descriptor.Descriptor(
  name='Ball',
  full_name='Ball',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='Ball.pos', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vel', full_name='Ball.vel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=293,
)


_GAMESTATE = _descriptor.Descriptor(
  name='GameState',
  full_name='GameState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_state', full_name='GameState.current_state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='team', full_name='GameState.team', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_team', full_name='GameState._team',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=295,
  serialized_end=375,
)


_POSSESSION = _descriptor.Descriptor(
  name='Possession',
  full_name='Possession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='balance', full_name='Possession.balance', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=406,
)


_TRACKING = _descriptor.Descriptor(
  name='Tracking',
  full_name='Tracking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='geometry', full_name='Tracking.geometry', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='team_color', full_name='Tracking.team_color', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ball', full_name='Tracking.ball', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='robots', full_name='Tracking.robots', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opposites', full_name='Tracking.opposites', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_state', full_name='Tracking.game_state', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='possession', full_name='Tracking.possession', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_geometry', full_name='Tracking._geometry',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_ball', full_name='Tracking._ball',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_game_state', full_name='Tracking._game_state',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_possession', full_name='Tracking._possession',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=409,
  serialized_end=686,
)

_ROBOT.fields_by_name['color'].enum_type = commons__pb2._COLORS
_ROBOT.fields_by_name['pos'].message_type = commons__pb2._VECTOR
_ROBOT.fields_by_name['vel'].message_type = commons__pb2._VECTOR
_BALL.fields_by_name['pos'].message_type = commons__pb2._VECTOR
_BALL.fields_by_name['vel'].message_type = commons__pb2._VECTOR
_GAMESTATE.fields_by_name['current_state'].enum_type = _STATES
_GAMESTATE.fields_by_name['team'].enum_type = commons__pb2._COLORS
_GAMESTATE.oneofs_by_name['_team'].fields.append(
  _GAMESTATE.fields_by_name['team'])
_GAMESTATE.fields_by_name['team'].containing_oneof = _GAMESTATE.oneofs_by_name['_team']
_TRACKING.fields_by_name['geometry'].message_type = _GEOMETRY
_TRACKING.fields_by_name['team_color'].enum_type = commons__pb2._COLORS
_TRACKING.fields_by_name['ball'].message_type = _BALL
_TRACKING.fields_by_name['robots'].message_type = _ROBOT
_TRACKING.fields_by_name['opposites'].message_type = _ROBOT
_TRACKING.fields_by_name['game_state'].message_type = _GAMESTATE
_TRACKING.fields_by_name['possession'].message_type = _POSSESSION
_TRACKING.oneofs_by_name['_geometry'].fields.append(
  _TRACKING.fields_by_name['geometry'])
_TRACKING.fields_by_name['geometry'].containing_oneof = _TRACKING.oneofs_by_name['_geometry']
_TRACKING.oneofs_by_name['_ball'].fields.append(
  _TRACKING.fields_by_name['ball'])
_TRACKING.fields_by_name['ball'].containing_oneof = _TRACKING.oneofs_by_name['_ball']
_TRACKING.oneofs_by_name['_game_state'].fields.append(
  _TRACKING.fields_by_name['game_state'])
_TRACKING.fields_by_name['game_state'].containing_oneof = _TRACKING.oneofs_by_name['_game_state']
_TRACKING.oneofs_by_name['_possession'].fields.append(
  _TRACKING.fields_by_name['possession'])
_TRACKING.fields_by_name['possession'].containing_oneof = _TRACKING.oneofs_by_name['_possession']
DESCRIPTOR.message_types_by_name['Geometry'] = _GEOMETRY
DESCRIPTOR.message_types_by_name['Robot'] = _ROBOT
DESCRIPTOR.message_types_by_name['Ball'] = _BALL
DESCRIPTOR.message_types_by_name['GameState'] = _GAMESTATE
DESCRIPTOR.message_types_by_name['Possession'] = _POSSESSION
DESCRIPTOR.message_types_by_name['Tracking'] = _TRACKING
DESCRIPTOR.enum_types_by_name['States'] = _STATES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Geometry = _reflection.GeneratedProtocolMessageType('Geometry', (_message.Message,), {
  'DESCRIPTOR' : _GEOMETRY,
  '__module__' : 'tracking_pb2'
  # @@protoc_insertion_point(class_scope:Geometry)
  })
_sym_db.RegisterMessage(Geometry)

Robot = _reflection.GeneratedProtocolMessageType('Robot', (_message.Message,), {
  'DESCRIPTOR' : _ROBOT,
  '__module__' : 'tracking_pb2'
  # @@protoc_insertion_point(class_scope:Robot)
  })
_sym_db.RegisterMessage(Robot)

Ball = _reflection.GeneratedProtocolMessageType('Ball', (_message.Message,), {
  'DESCRIPTOR' : _BALL,
  '__module__' : 'tracking_pb2'
  # @@protoc_insertion_point(class_scope:Ball)
  })
_sym_db.RegisterMessage(Ball)

GameState = _reflection.GeneratedProtocolMessageType('GameState', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTATE,
  '__module__' : 'tracking_pb2'
  # @@protoc_insertion_point(class_scope:GameState)
  })
_sym_db.RegisterMessage(GameState)

Possession = _reflection.GeneratedProtocolMessageType('Possession', (_message.Message,), {
  'DESCRIPTOR' : _POSSESSION,
  '__module__' : 'tracking_pb2'
  # @@protoc_insertion_point(class_scope:Possession)
  })
_sym_db.RegisterMessage(Possession)

Tracking = _reflection.GeneratedProtocolMessageType('Tracking', (_message.Message,), {
  'DESCRIPTOR' : _TRACKING,
  '__module__' : 'tracking_pb2'
  # @@protoc_insertion_point(class_scope:Tracking)
  })
_sym_db.RegisterMessage(Tracking)


# @@protoc_insertion_point(module_scope)
