from neonfc_ssl.strategies.still import Still
from neonfc_ssl.strategies.follow_pose import FollowPose
from neonfc_ssl.strategies.receiver import Receiver
from neonfc_ssl.strategies.ball_holder import BallHolder
from neonfc_ssl.strategies.goalkeeper import GoalKeeper
from neonfc_ssl.strategies.libero import Libero
from neonfc_ssl.strategies.right_back import RightBack
from neonfc_ssl.strategies.left_back import LeftBack
from neonfc_ssl.strategies.base_strategy import BaseStrategy
from neonfc_ssl.strategies.test import Test
from neonfc_ssl.strategies.passer import Passer
from neonfc_ssl.strategies.prepare_ballplacement import PrepBallPlacement
from neonfc_ssl.strategies.prepare_kickoff import PrepKickoff
from neonfc_ssl.strategies.prepare_penalty import PrepPenalty
from neonfc_ssl.strategies.prepare_gk_penalty import PrepGKPenalty
from neonfc_ssl.strategies.prepare_bh_penalty import PrepBHPenalty
