from neonfc_ssl.strategies.still import Still
from neonfc_ssl.strategies.receiver import Receiver
from neonfc_ssl.strategies.ball_holder import BallHolder
from neonfc_ssl.strategies.goalkeeper import GoalKeeper
from neonfc_ssl.strategies.libero import Libero
from neonfc_ssl.strategies.right_back import RightBack
from neonfc_ssl.strategies.left_back import LeftBack
from neonfc_ssl.strategies.base_strategy import BaseStrategy
from neonfc_ssl.strategies.test import Test
from neonfc_ssl.strategies.passer import Passer
from neonfc_ssl.strategies.prepare_ballplacement import BallPlacement
from neonfc_ssl.strategies.prepare_kickoff import Kickoff
from neonfc_ssl.strategies.prepare_penalty import Penalty
